backward() vs autograd.grad()

In [21]:
import torch

class sampleClass(torch.nn.Module):
	def __init__(self) -> None:
		super().__init__()
		self.linear1 = torch.nn.Linear(3, 4)
		self.relu = torch.nn.ReLU()
		self.linear2 = torch.nn.Linear(4, 2)
		self.ff = torch.nn.Sequential(
		self.linear1,
		self.relu,
		self.linear2
	)
	def forward(self, x):
		return self.ff(x)

In [22]:
# loss.backward()
model = sampleClass()
model.train()

target = torch.tensor([1., -1.0])

input = torch.randn(2,3 , requires_grad=True)
output = model(input)
loss = torch.square(target-output).mean(dim=-1)
loss = torch.sum(loss)
loss.backward()

# 모델의 Weight와 Bias와 Input들의 grad에 미분 값들이 저장된다.
print("Input\n",input.grad)
for name, param in model.named_parameters():
    print(name, '\n', param.grad)
    print()


Input
 tensor([[ 0.3156,  0.0134, -0.3926],
        [ 0.2629, -0.0848, -0.2791]])
linear1.weight 
 tensor([[ 1.7027,  2.5381, -0.2534],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0880,  0.3149, -0.2677],
        [ 0.0000,  0.0000,  0.0000]])

linear1.bias 
 tensor([1.9597, 0.0000, 0.2281, 0.0000])

linear2.weight 
 tensor([[-1.1070,  0.0000, -0.6943,  0.0000],
        [ 1.4367,  0.0000,  0.9439,  0.0000]])

linear2.bias 
 tensor([-2.6285,  3.2862])



In [23]:
# torch.autograd.grad
model2 = sampleClass()
model2.train()

input = torch.randn(2,3 , requires_grad=True)
output = model2(input)
loss = torch.square(target-output).mean(dim=-1)
loss = torch.sum(loss)
# input에 대한 loss의 기울기만 반환만 함 (grad에 저장 X)
print(torch.autograd.grad(outputs=loss, inputs=input))

# 모델의 Weight와 Bias와 Input들의 grad에 미분 값들이 저장되지 않는다.
print("Input\n",input.grad)
for name, param in model2.named_parameters():
    print(name, '\n', param.grad)
    print()


(tensor([[ 0.1363, -0.0687, -0.0417],
        [ 0.1086, -0.0610, -0.0049]]),)
Input
 None
linear1.weight 
 None

linear1.bias 
 None

linear2.weight 
 None

linear2.bias 
 None



In [ ]:
# optimizer.zero_grad() # Reset gradients
# for i, (inputs, labels) in enumerate(dataloader):
#     outputs = model(inputs)
#     loss = criterion(outputs, labels)
#     loss.backward() # Gradients are accumulated
    
#     if (i + 1) % gradient_accumulation_steps == 0:
#         optimizer.step() # Update weights
#         optimizer.zero_grad() # Reset gradients for the next iteration

