In [90]:
from tempfile import mkdtemp
import numpy as np
import os

# 임시 경로에 파일 생성
filename = os.path.join(mkdtemp(), 'newfile.dat')

# memmap 설정		# mode
dtype = 'float32'	# r: 기존 파일 읽기
mode = 'w+'			# w+: 새로운 파일 생성, 기존 파일 읽기/쓰기
shape = (3, 4)		# r+: 기존 파일 읽기/쓰기
					# default: r+

# 임의의 데이터 생성
data = np.array(np.arange(12)).reshape(3, 4)

# fp라는 memmap 객체를 생성
fp = np.memmap(filename=filename, dtype=dtype, mode=mode, shape=shape)

# fp에 데이터 저장
fp[:] = data[:]

# fp의 변경 사항을 디스크의 파일에 저장
fp.flush()

# 디스크의 파일에 저장된 데이터를 가져오기
fp2 = np.memmap(filename=filename, dtype=dtype, mode='r+', shape=shape)

print(fp2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
